// Test wrapper：为需要 react-query 的组件提供 QueryClientProvider + LocaleProvider。

import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { NextIntlClientProvider } from 'next-intl'
import { ReactNode } from 'react'
import { render } from '@testing-library/react'

// 完整 en messages（覆盖所有测试涉及的 namespace）
const enMessages = {
  agent: {
    title: 'Agent',
    pairingCode: 'Pairing Code',
    rotate: 'Rotate Code',
    rotateConfirm: 'Confirm?',
    rotateSuccess: 'Rotated',
    copyHint: 'Run agent with:',
    setupInstructions: 'Run on machine:',
    status: { pending: 'pending', online: 'online', offline: 'offline' },
    lastSeen: 'Last seen',
    publicKey: 'Public Key',
    publicKeyNotAvailable: 'Not available until agent connects',
    never: 'Never',
    copy: 'Copy',
    copied: 'Copied',
    copyFailed: 'Copy failed',
    rotateFailed: 'Failed to rotate code',
    copiedNewCode: 'New code copied to clipboard',
    codeCopiedManualHint: "Couldn't copy automatically. Select and copy manually.",
    confirmRotate: 'Click again to confirm',
    maskedCodeHint: 'The pairing code is masked. Rotate to get a full code.',
    model: {
      server: 'wakewake server',
      agent: 'LAN agent',
      device: 'Your devices',
      linked: 'Connected',
      missing: 'Not connected yet',
      broken: 'Disconnected',
    },
    guide: {
      whereTitle: 'Run the agent on an always-on machine in your home network',
      whereDesc: 'The agent must share a router with the devices you want to wake.',
      commandLabel: 'Launch command',
      copyCommand: 'Copy command',
      waiting: 'Waiting for the agent to connect — this page updates automatically.',
      tabLinux: 'Linux',
      tabDocker: 'Docker',
    },
    online: { title: 'Agent connected', desc: 'The agent is running.', cta: 'Go to devices' },
    offline: {
      title: 'Agent disconnected',
      desc: 'The agent was paired before.',
      repairHint: 'Rotate the pairing code to pair a new machine.',
    },
    advanced: 'Advanced',
    advancedConfigTitle: 'Launch with a config file',
    advancedConfigDesc: 'Save as ~/.wakewake/config.toml.',
    service: {
      title: 'Run at boot (bare-metal installs)',
      desc: 'Install as a systemd service after the first foreground run. Docker installs do not need this.',
    },
  },
  agents: { title: 'Agent', comingSoon: 'soon' },
  device: {
    syncing: 'Syncing',
    syncError: 'Sync error',
    agentOnline: 'Agent online',
    agentOffline: 'Agent offline',
    cloudSynced: 'Bemfa synced',
    cloudError: 'Bemfa error: {error}',
    cloudNone: 'Bemfa none',
    wakeUnavailable: 'Wake unavailable',
    addDevice: '+ Add device',
    deleteDialogTitle: 'Delete device',
    deleteDialogDesc: 'Delete this device?',
  },
  integrations: {
    title: 'Integrations',
    comingSoon: 'soon',
    add: 'Add',
    bemfaDesc: 'desc',
    bemfaUidHint: 'uid hint',
    connect: 'Connect Bemfa',
    connected: 'Connected',
    notConnected: 'Not connected',
    enable: 'Enable',
    disable: 'Disable',
    edit: 'Configure',
    cancel: 'Cancel',
    save: 'Save',
    deleteConfirm: 'Delete?',
    deleteRemoved: 'Removed',
    configHint: 'configHint',
    editConfig: 'Edit configuration',
    placeholderSecret: 'placeholder',
    stateConnected: 'Connected',
    stateConnecting: 'Connecting…',
    stateConnectingHint: 'connecting hint',
    stateAgentOffline: 'Agent offline',
    stateAgentOfflineHint: 'agent offline hint',
    stateDisconnected: 'MQTT not connected',
    stateDisconnectedHint: 'disconnected hint',
    stateError: 'Sync error',
    stateDisabled: 'Paused',
    stateDisabledHint: 'disabled hint',
    devicesSynced: '{count} devices synced',
    lastError: 'Last error: {error}',
    v2Optional: 'v2 API credentials (optional)',
    v2Toggle: 'Use v2 API',
    v2Hint: 'v2 hint',
    mijiaGuide: 'How to enable voice control with Xiao Ai',
    mijiaStep1: 'step1',
    mijiaStep2: 'step2',
    mijiaStep3: 'step3',
    mijiaStep4: 'step4 {device}',
    mijiaWarning: 'warning',
    deleteDialogTitle: 'Remove integration',
    deleteDialogDesc: 'Disconnect Bemfa?',
    toggleSuccess: '{action} succeeded',
    toggleFailed: '{action} failed',
  },
  navigation: {
    devices: 'Devices',
    agent: 'Agent',
    integrations: 'Integrations',
    history: 'History',
    admin: 'Admin',
  },
  // admin namespace：测试用兜底值（覆盖 admin 页面用到的 key）。
  admin: {
    title: 'Admin',
    users: 'User Management',
    devices: 'Devices',
    agents: 'Agents',
    activity: 'Activity',
    activityDesc: 'Recent sign-in and audit events',
    integrations: 'Integrations',
    integrationsDesc: 'Cloud sync integrations',
    wakes: 'Wakes',
    wakesDesc: 'Wake event history',
    maintenance: { title: 'Maintenance' },
    maintenanceDesc: 'System maintenance mode',
    devicesDesc: 'Devices and sync status',
    agentsDesc: 'Connected agents',
    auditLog: 'Audit Log',
    loading: 'Loading...',
    empty: 'No users found.',
    emptyDevices: 'No devices found.',
    emptyAgents: 'No agents found.',
    emptyAudit: 'No audit entries yet.',
    manageUsers: 'manage users',
    manageDevices: 'manage devices',
    manageAgents: 'manage agents',
    manageAuditLog: 'manage audit',
    userManagement: 'User Management',
    userManagementDesc: 'desc',
    searchUsers: 'Search email...',
    searchAgents: 'Search agent or user...',
    searchDevices: 'Search device or user...',
    lastLogin: 'Last login',
    never: 'Never',
    thisIsYou: 'you',
    statusActive: 'Active',
    filterAll: 'All',
    filterClear: 'Clear',
    disable: 'Disable',
    enable: 'Enable',
    resync: 'Resync',
    disconnect: 'Disconnect',
    resetPassword: 'Reset Password',
    forceVerify: 'Force verify',
    cancel: 'Cancel',
    confirm: 'Confirm',
    disableSuccess: 'ok',
    enableSuccess: 'ok',
    resyncSuccess: 'ok',
    disconnectSuccess: 'ok',
    resetPasswordSuccess: 'ok',
    verifyEmailSuccess: 'ok',
    resetPasswordTitle: 't',
    resetPasswordDesc: 'd',
    resetPasswordWarning: 'w',
    newPassword: 'New password',
    newPasswordPlaceholder: 'p',
    passwordTooShort: 'short',
    forceVerifyTitle: 't',
    forceVerifyDesc: 'd',
    disableDialogTitle: 'Disable user',
    disableDialogDesc: 'Disable this user?',
    disableDialogReason: 'Reason (optional):',
    disableDialogReasonPlaceholder: 'e.g. Abuse',
    resetDialogTitle: 'Reset password',
    resetDialogDesc: 'Reset password for this user?',
    resetDialogPasswordLabel: 'New password (min 8):',
    you: 'you',
    emailVerified: 'Verified',
    verified: 'Verified',
    notVerified: 'Unverified',
    email: 'Email',
    role: 'Role',
    status: 'Status',
    created: 'Created',
    actions: 'Actions',
    active: 'Active',
    disabled: 'Disabled',
    superuser: 'Superuser',
    user: 'User',
    statUsers: 'Total users',
    statActiveUsers: '{n} active',
    statAgents: 'Agents',
    statOnlineAgents: '{n} / {total} online',
    statDevices: 'Devices',
    statIntegrations: '{n} integrations',
    statWakes: 'Wake events',
    statSyncing: 'Devices syncing',
    statSyncingHint: 'hint',
    statSyncError: 'Devices sync error',
    statSyncErrorHint: 'hint',
    attentionTitle: 'attention',
    attentionDesc: 'desc',
    recentActions: 'Recent',
    viewAllAudit: 'view all',
    colDevice: 'Device',
    colOwner: 'Owner',
    colSyncStatus: 'Sync status',
    colUpdated: 'Updated',
    colAgent: 'Agent',
    colStatus: 'Status',
    colLastSeen: 'Last seen',
    colTime: 'Time',
    colActor: 'Actor',
    colAction: 'Action',
    colTarget: 'Target',
    colDetail: 'Detail',
    colProvider: 'Provider',
    colLastReport: 'Last report',
    colType: 'Type',
    colResult: 'Result',
    operationsTitle: 'Operations',
    systemTitle: 'System',
    disconnectDisabledHint: 'hint',
    filterSynced: 'Synced',
    filterSyncing: 'Syncing',
    filterSyncError: 'Sync error',
    sync_synced: 'Synced',
    sync_syncing: 'Syncing',
    sync_sync_error: 'Sync error',
    agent_online: 'Online',
    agent_offline: 'Offline',
    agent_pending: 'Pending',
    pagination: {
      showing: 'Showing {from}-{to} of {total}',
      prev: 'Previous',
      next: 'Next',
      perPage: '{count} / page',
    },
  },
  health: {
    healthy: 'All systems operational',
    devicesNeedAttention:
      '{count, plural, one {# device needs attention} other {# devices need attention}}',
  },
  common: {
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  error: {
    SYNCING: 'syncing',
    INTERNAL_ERROR: 'internal',
    USER_DISABLED: 'disabled',
    AUTH_REQUIRED: 'auth',
    TOKEN_EXPIRED: 'expired',
    INVALID_CREDENTIALS: 'bad creds',
  },
}

export function renderWithProviders(ui: ReactNode) {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  })
  return {
    queryClient,
    ...render(
      <QueryClientProvider client={queryClient}>
        <NextIntlClientProvider locale="en" messages={enMessages}>
          {ui}
        </NextIntlClientProvider>
      </QueryClientProvider>,
    ),
  }
}
